version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo Building Docker image
      - docker build -t rails-app .
      - docker tag rails-app:latest $ECR_URI:latest

  post_build:
    commands:
      - echo Pushing Docker image
      - docker push $ECR_URI:latest
